<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>employee-directory-eks-demo</UserSecretsId>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Certificates\**" />
    <Compile Remove="EmployeeDirectory.Tests\**" />
    <Compile Remove="EmployeeDirectory.Test\**" />
    <Compile Remove="publish\**" />
    <Content Remove="Certificates\**" />
    <Content Remove="EmployeeDirectory.Tests\**" />
    <Content Remove="EmployeeDirectory.Test\**" />
    <Content Remove="publish\**" />
    <EmbeddedResource Remove="Certificates\**" />
    <EmbeddedResource Remove="EmployeeDirectory.Tests\**" />
    <EmbeddedResource Remove="EmployeeDirectory.Test\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="Certificates\**" />
    <None Remove="EmployeeDirectory.Tests\**" />
    <None Remove="EmployeeDirectory.Test\**" />
    <None Remove="publish\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\UnitTest1.cs" />
  </ItemGroup>

  <ItemGroup>
    <!-- EF Core + MySQL (Pomelo is the community provider Amazon RDS MySQL guides commonly point to) -->
    <PackageReference Include="AWSSDK.S3" Version="4.0.102.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- S3 upload for employee photos -->
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.301" />

    <!-- Health checks used by k8s liveness/readiness probes -->
    <PackageReference Include="AspNetCore.HealthChecks.MySql" Version="8.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="deploy\" />
    <Folder Include="docs\" />
    <Folder Include="terraform\" />
  </ItemGroup>

</Project>
